<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PackageId>HWSistemas.Danfe</PackageId>
    <Version>1.0.8</Version>
    <Authors>hwsistemas</Authors>
    <Company>hwsitemas</Company>
    <!-- <PackageReadmeFile>README.md</PackageReadmeFile> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfClown.NetStandard" Version="0.2.0-beta" />
  </ItemGroup>
</Project>